# example netlify.toml
[build]
    functions = "netlify/functions"
publish = ""
[[redirects]]
    force = true
    from = "/api/*"
    status = 200
    to = "/.netlify/functions/api/:splat"
#
#[build]
#functions = "netlify/functions"
#
#[[redirects]]
#from = "/api/*"
#to = "/.netlify/functions/api"
#status = 200
#timeout = 60  # Increase timeout
#memory = 2048  # Increase memory if needed

